version: "2"
services:
  react:
    image: node:10.15.0
    volumes:
      - .:/frontend
    working_dir: /frontend
    ports:
      - "3000:3000"
    command: /bin/bash -c "npm install -g --ignore-scripts && npm install protobufjs -g --ignore-scripts && node node_modules/@tensorflow/tfjs/node_modules/protobufjs/scripts/postinstall.js && npm start"